name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    strategy:
      matrix:
        go-version: ['1.19']
    runs-on: ubuntu-22.04
    env:
      CGO_ENABLED: '0'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go v${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Client unit tests
        run: |
          make test-client
